apiVersion: apps/v1
kind: Deployment
metadata:
  name: looks-api-dotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: looks-api-dotnet
  template:
    metadata:
      labels:
        app: looks-api-dotnet
    spec:
      containers:
      - name: nginx
        image: thewapp.azurecr.io/looks-api-dotnet:latest  # Replace 'myacr' with your ACR name
        ports:
        - containerPort: 80
          name: looks-api-port
