name: Deploy to AKS

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet publish -c Release -o out

    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login to ACR
      run: az acr login --name thewapp #Azure container registry name

    - name: Build and Push Docker Image
      run: |
        docker build -t thewapp.azurecr.io/looks-api-dotnet:latest .
        docker push thewapp.azurecr.io/looks-api-dotnet:latest

    - name: Azure Kubernetes Set Context
      uses: azure/aks-set-context@v3.2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: "aks-the-wapp"
        resource-group: "the-wapp"

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml